name: Plant Care Add-ons
description: Custom add-ons for plant care.
slug: plant_care_addons
version: "1.0.0"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
add-ons:
  - plant-care-addon



